### ISSUE TITLE
Include setup instructions

### ISSUE THREAD

**Issue by torcasitas** [jfranz/ember-cli-soundmanager-shim#1]
Hi I'm trying to set it up as shim module on an Ember app but didn't manage to get it working.

My goal was to reference the soundmanager library like this on a Controller/Component: 

import soundManager from 'ember-cli-soundmanager-shim/soundmanager2-shim';

Thanks

**Comment by jfranz** [comment]
Hey @torcasitas sorry I didn't see this before. I've been meaning to create an addon for this but for now please see the updated README with usage instructions.
